### ISSUE TITLE
Examples do not work on Safari

### ISSUE THREAD

**Issue by taylorhadden** [rozek/svelte-drag-and-drop-actions#1]
When I attempt to drag in any of the examples in Safari, no dragging happens. In the console, I can see that the "drag start" and "drag end" messages are fired one right after the other, despite not releasing the mouse button.

I'm using Safari 15.1.

**Comment by rozek** [comment]
ok, give me some time to investigate - thanks for the notice!

Do we talk about Safari on macOS?

**Comment by taylorhadden** [comment]
Yes, this is Safari on macOS 12.0.1

**Comment by rozek** [comment]
I won't find the time to investigate today, but will do so tomorrow morning...

**Comment by rozek** [comment]
Ok, I can confirm that the examples do not work on Safari 15.0 under macOS 11.6 (that's my configuration) - although the problem seems to be in the REPL itself. I'll see what I can do to get everything running again

**Comment by rozek** [comment]
as far as I can tell right now, the problem occurs in ANY example and is NOT related to svelte-drag-and-drop-actions!

**Comment by taylorhadden** [comment]
That's interesting. I assume drag-drop works okay outside of the the REPL?

**Comment by jrmoynihan** [comment]
Seemed to be having troubles in Firefox too.  Is that just in the REPL as well?

**Comment by kkarpeev** [comment]
Hello! Firefox has the same problem, sadly...
Tried ex from below and bezier and some others (with a free movement). Dragging element just stacks to (0,0) on mouse down.
[Like here](https://svelte.dev/repl/52e662d6220d447495be8cd8851322b9?version=4.2.2)

FF version 118.0.2 (64-bit)
Also tried Svelte version=3

**Comment by rozek** [comment]
I just tested the examples on Safari Version 16.6 (18615.3.12.11.2) - and they seem to work.

The Firefox problem still exists due to a bug in the browser itself (see issue #5) - I'm looking for a workaround, but right now it seems as if it the best solution would be to choose another browser...

**Comment by rozek** [comment]
the Safari problem seems to be solved by an update of the browser itself
