### ISSUE TITLE
Drop zone is set to draggable

### ISSUE THREAD

**Issue by adamnyberg** [rozek/svelte-drag-and-drop-actions#3]
Should `use:asDropZone` really add `draggable="true"` to the element? 

This seems always to happen. See any of the examples listed in the readme, or [here is a link to the first example](https://svelte.dev/repl/8e0ec7bf90bf4ad889b48ff6029bf1f6?version=3.59.1). 

![SCR-20230522-our](https://github.com/rozek/svelte-drag-and-drop-actions/assets/1665236/77d0deb7-5503-4f0d-9704-1a7b65c790b3)

**Comment by nfplay** [comment]
This looks like a bug, a dropzone should not be draggable by default.

**Comment by rozek** [comment]
Thanks for the hint - I just removed the faulty line and re-published everything
