### ISSUE TITLE
no exports condition for svelte

### ISSUE THREAD

**Issue by drmule** [rozek/svelte-drag-and-drop-actions#7]
[vite-plugin-svelte] WARNING: The following packages have a svelte field in their package.json but no exports condition for svelte.

https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#missing-exports-condition

Corrected by adding:

"exports": {
    ".": {
      ...,
      "svelte": "./dist/svelte-drag-and-drop-actions.js"
    },
    "./package.json": "./package.json"
  },

**Comment by rozek** [comment]
Thank you very much for this hint - I've just updated "package.json", rebuilt and re-published the library.
